[package]
name = "neolink"
description = "A standards-compliant bridge to Reolink IP cameras"
version = "0.4.0"
authors = ["George Hilliard <thirtythreeforty@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "crates/*",
]
